apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.schedule }}" # Define the schedule in cron format
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              env:
                - name: ENVIRONMENT
                  value: {{ .Values.environment | quote }}
                {{- if .Values.envFromSecrets }}
                {{- range $key, $value := .Values.envFromSecrets }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $value.secretName }}
                      key: {{ $value.key }}
                {{- end }}
                {{- end }}
              resources:
                requests:
                  memory: {{ .Values.resources.requests.memory }}
                  cpu: {{ .Values.resources.requests.cpu }}
                limits:
                  memory: {{ .Values.resources.limits.memory }}
                  cpu: {{ .Values.resources.limits.cpu }}
          restartPolicy: {{ .Values.restartPolicy | default "OnFailure" }}