apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-parent-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/meditrack-org/mt-argocd-applications.git 
    targetRevision: main # Branch or tag
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true