global:
  revisionHistoryLimit: 3  

controller:
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true  

configs:
  cm:
    timeout.reconciliation: 45s  
    exec.enabled: true
    admin.enabled: true
    url: "http://argocd.homelab-app.me"
    tls.insecure: "true"

  credentialTemplates:
    https-creds:
      url: https://github.com/devops-homelab
      password: xxx
      username: njay4928

redis-ha:   
  enabled: false  

server:
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true  
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - argocd.homelab-app.me
  extraArgs:
    - "--insecure"
    
repoServer:
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true  

applicationSet:
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true  
