apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: doctor-record-service-dev
  annotations:
     reloader.stakater.com/auto: "true"
type: Opaque
data:
  username: ZG9hZG1pbgo=
  password: QVZOU19SRElPdUpqVWRRQlpyREozNVMwCg==
  name: aG9tZWxhYgo=
  host: aG9tZWxhYi1wb3N0Z3Jlc3FsLWRiLWRldi1wZy1kby11c2VyLTE4ODM4ODMwLTAuZy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb20K
  port: MjUwNjAK