apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: doctor-record-service-dev
  annotations:
     reloader.stakater.com/auto: "true"
type: Opaque
data:
  username: aG9tZWxhYi11c2VyCg==
  password: QVZOU19XX0hKMXBtN1pkQXBxWmhjVE1XCg==
  name: aG9tZWxhYgo=
  host: aG9tZWxhYi1wb3N0Z3Jlc3FsLWRiLWNsdXN0ZXItZGV2LXBnLWRvLXVzZXItMTg4Mzg4MzAtMC5oLmRiLm9uZGlnaXRhbG9jZWFuLmNvbQo=
  port: MjUwNjAK